# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/aide
  block:

    - name: Set OS variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family|lower }}.yml"
        - "default.yml"

    - name: CIS | Ensure AIDE is installed
      become: true
      ansible.builtin.package:
        name: "{{ aide_packages }}"
        state: "{{ aide_state }}"

    - name: Check for existing AIDE db
      become: true
      ansible.builtin.stat:
        path: "{{ aide_cur_db_file }}"
      register: 'aide_db'
      changed_when: 'not aide_db.stat.exists'
      notify: 'Initialize AIDE db'
      when:
        - aide_state == 'present'

    - name: Ensure permissions on AIDE db are configured
      become: true
      ansible.builtin.file:
        name: "{{ aide_cur_db_file }}"
        owner: 'root'
        group: 'root'
        mode: '0600'
      when:
        - aide_state == 'present'
        - aide_db.stat.exists

    - name: Remove AIDE db path
      become: true
      ansible.builtin.file:
        name: '/var/lib/aide'
        state: absent
      when:
        - aide_state != 'present'

    - name: Remove AIDE log
      become: true
      ansible.builtin.file:
        name: '/var/log/aide'
        state: absent
      when:
        - aide_state != 'present'

    - name: CIS | Ensure filesystem integrity is regularly checked
      become: true
      ansible.builtin.template:
        src: 'etc/cron.d/aide.j2'
        dest: '/etc/cron.d/aide'
        owner: 'root'
        group: 'root'
        mode: '0644'
      when:
        - aide_state == 'present'

    - name: Remove AIDE cron.d schedule
      become: true
      ansible.builtin.file:
        name: '/etc/cron.d/aide'
        state: absent
      when:
        - aide_state != 'present'

    # Flush any handlers that we might have called
    - name: Flush handlers
      ansible.builtin.meta:
        flush_handlers

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_aide'
