# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Initialize AIDE db
  become: true
  ansible.builtin.command:
    cmd: "{{ aide_init_command }}"
  notify: Activate AIDE db
  when:
    - 'not aide_db.stat.exists'

- name: Activate AIDE db
  become: true
  ansible.builtin.copy:
    src: "{{ aide_new_db_file }}"
    remote_src: true
    dest: "{{ aide_cur_db_file }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: Remove AIDE newdb

- name: Remove AIDE newdb
  become: true
  ansible.builtin.file:
    name: "{{ aide_new_db_file }}"
    state: absent
